version: '3.8'
services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flowable:
    image: flowable/all-in-one
    ports:
      - "8081:8080"
    environment:
      - FLOWABLE_DB_PASSWORD=password
      - FLOWABLE_DB_URL=jdbc:postgresql://postgres:5432/flowable?charSet=UTF-8
    depends_on:
      - postgres

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - flowable
    environment:
      - DB_URL=postgres://postgres:password@postgres:5432/postgres?sslmode=disable

volumes:
  postgres_data:
